version: '3.8'

services:
  # ==================== FRONTEND ====================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - api-gateway
    restart: unless-stopped

  # ==================== API GATEWAY ====================
  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    depends_on:
      - auth-service
      - user-service
      - topic-service
      - test-service
    restart: unless-stopped

  # ==================== MICROSERVICES ====================
  auth-service:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  mail-service:
    build:
      context: ./backend/mail-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  user-service:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    environment:
      - NODE_ENV=production
    depends_on:
      - db-users
    restart: unless-stopped

  topic-service:
    build:
      context: ./backend/topic-service
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    env_file:
      - ./backend/topic-service/.env
    depends_on:
      - db-topics
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  test-service:
    build:
      context: ./backend/test-service
      dockerfile: Dockerfile
    ports:
      - "5006:5006"
    env_file:
      - ./backend/test-service/.env
    depends_on:
      - db-tests
    restart: unless-stopped

  # ==================== DATABASES ====================
  db-users:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: user_db
    ports:
      - "3308:3306"
    volumes:
      - mysql_users_data:/var/lib/mysql

  db-topics:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: topic_db
    ports:
      - "3309:3306"
    volumes:
      - mysql_topics_data:/var/lib/mysql

  db-tests:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: test_db
      MYSQL_USER: app_user          # <-- thêm user
      MYSQL_PASSWORD: "apppassword" # <-- và password
    ports:
      - "3310:3306"
    volumes:
      - mysql_tests_data:/var/lib/mysql

volumes:
  mysql_users_data:
  mysql_topics_data:
  mysql_tests_data: