name: Backend Unit Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  user-service-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/user-service
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm test

  topic-service-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/topic-service
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm test
  test-service-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/test-service
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm test 